### ISSUE TITLE
error when python3-venv not installed

### ISSUE THREAD

**Issue by mahwd** [munisisazade/create-django-app#4]
Add Contributing #1

When contributing to this repository, please first discuss the change you wish to make via issue,
email, or any other method with the owners of this repository before making a change.

Please note we have a code of conduct, please follow it in all your interactions with the project.
![image](https://user-images.githubusercontent.com/25174247/37024656-e78d8a58-2142-11e8-8a4b-c61138432314.png)

**Comment by munisisazade** [comment]
@mahwd Thanks for using my tool, I already fix that please check new version #6 and install it.
